### Pytorch Tensor 생성, shape, 차원, 타입
* torch Tensor는 scalar값, python list, numpy array, 기존 tensor등을 기반으로 생성할 수 있음.
* tensor의 형태(shape)는 shape 속성 또는 size() 메소드로 확인 

In [1]:
import numpy as np
import torch

list_01 = [1, 2, 3]
ts_01 = torch.tensor(list_01)
ts_02 = torch.tensor([[1, 2, 3],
                      [2, 3, 4]
                     ])
ts_03 = torch.tensor([
                      [[1, 2, 3],
                       [2, 3, 4]],
                      [[3, 4, 5],
                       [4, 5, 6]]
                     ]) 
print('ts_01:', ts_01.shape, 'ts_02 shape:', ts_02.shape, 'ts_03 shape:', ts_03.shape) 

ts_01: torch.Size([3]) ts_02 shape: torch.Size([2, 3]) ts_03 shape: torch.Size([2, 2, 3])


In [2]:
np.array([1, 2, 3]).shape

(3,)

#### Tensor의 shape/size 및 차원
* pytorch tensor는 shape 속성 및 size() 메소드를 통해 torch.Size 오브젝트를 반환하여 tensor의 형태(shape)를 제공
* shape 속성과 size() 메소드는 거의 동일.
* 순수하게 차원 정보만 알고 싶을 때는 ndim 속성을 이용

In [3]:
print(ts_02.shape, ts_02.size())

torch.Size([2, 3]) torch.Size([2, 3])


In [4]:
print(ts_02.shape[0], ts_02.shape[1], ts_02.size(0), ts_02.size(1), ts_02.size()[0]) 

2 3 2 3 2


In [5]:
ts_02.ndim

2

#### tensor 데이터 타입
* tensor내의 값은 동일한 데이터 타입을 가짐. dtype 속성으로 확인
* 데이터 타입은 생성시에 지정하거나, type() 또는 to() 메소드를 이용하여 변환. 

In [6]:
ts_01 = torch.tensor([1.0, 2, 3])
print(ts_01.dtype)

torch.float32


In [7]:
ts_01 = torch.tensor([1, 2, 3], dtype=torch.float32)
print(ts_01.dtype)  # torch.float32

torch.float32


In [8]:
ts_01_1 = ts_01.int() #int32로 변환
print(ts_01_1.dtype)

ts_01_2 = ts_01.float() #float32 변환
print(ts_01_2.dtype)

torch.int32
torch.float32


In [9]:
ts_01_1 = ts_01.type(torch.int64)
print(ts_01_1.dtype)

ts_01_2 = ts_01.type(torch.int8) # float32/float64
print(ts_01_2.dtype)

torch.int64
torch.int8


In [10]:
ts_01_1 = ts_01.to(torch.int64)
print(ts_01_1.dtype)

ts_01_2 = ts_01.to(torch.int8) # float32/float64
print(ts_01_2.dtype)

torch.int64
torch.int8


#### numpy array와 pytorch tensor간 상호 변환

In [11]:
# numpy array를 tensor로 변환. 
arr_01 = np.array([1, 2])
ts_01 = torch.tensor(arr_01)
ts_02 = torch.from_numpy(arr_01)
print(type(arr_01), ts_01, ts_02)

<class 'numpy.ndarray'> tensor([1, 2]) tensor([1, 2])


In [12]:
# tensor를 array 또는 list로 변환. 
arr_01_1 = ts_01.numpy()
list_01 = ts_01.tolist()
print(arr_01_1, type(arr_01_1), list_01, type(list_01))

[1 2] <class 'numpy.ndarray'> [1, 2] <class 'list'>


In [ ]:
import numpy as np
import torch

ts_01 = torch.tensor([1, 2])
ts_01_1 = ts_01.to('cpu')
# ts_01_1 = ts_01.to('cuda')
# 아래는 오류를 발생. device가 cuda에 있는 tensor의 경우 numpy() 메소드를 바로 호출 할 수 없음.
arr_01_1 = ts_01_1.numpy() #  ts_01_1.cpu().numpy()를 호출해야 함. 

In [15]:
# tensor.from_numpy(array) 수행 시 생성된 tensor는 입력된 array와 메모리를 공유
# 입력 array가 변경될 경우 tensor도 같이 변경됨.
arr_01 = np.array([1, 2])
ts_01 = torch.from_numpy(arr_01)
print('arr_01:', arr_01, 'ts_01:', ts_01)

arr_01[0] = 0
print('arr_01:', arr_01, 'ts_01:', ts_01)

# clone() 을 사용하여 tensor를 복제
ts_02 = ts_01.clone()
arr_01[0] = 100
print('arr_01:', arr_01, 'ts_01:', ts_01, 'ts_02:', ts_02)

arr_01: [1 2] ts_01: tensor([1, 2])
arr_01: [0 2] ts_01: tensor([0, 2])
arr_01: [100   2] ts_01: tensor([100,   2]) ts_02: tensor([0, 2])


#### tensor를 편리하게 생성하기 - arange, zeros, ones

In [16]:
seq_ts = torch.arange(10)
print(seq_ts)
print(seq_ts.dtype, seq_ts.shape)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.int64 torch.Size([10])


In [17]:
torch.zeros(size=(3, 2), dtype=torch.int32).dtype

torch.int32

In [18]:
zero_ts = torch.zeros(size=(3, 2), dtype=torch.int32)  #문자열 'int32'는 안됨. 
print(zero_ts)
print(zero_ts.dtype, zero_ts.shape)

one_ts = torch.ones(3, 2, dtype=torch.int16) # tuple을 사용하지 않아도 됨
print(one_ts)
print(one_ts.dtype, one_ts.shape)

tensor([[0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int32)
torch.int32 torch.Size([3, 2])
tensor([[1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)
torch.int16 torch.Size([3, 2])


#### random 값 생성하기
* rand()은 기본으로 0 ~ 1(1은 제외)사이의 균일 분포(uniform distribution) random 값을 생성.
* randint()는 random 정수값을 생성
* randn()은 정규 분포(Normal distribution) random 값을 생성. 

In [20]:
torch.manual_seed(2025)  # random 수행 시 마다 동일 값 생성을 위한 seed값 할당. 

ts_01 = torch.rand(size=(3, 4)) # 0 ~ 1 사이의 float32 random값. 1제외
print('ts_01:\n', ts_01, ts_01.dtype)
print(ts_01.min(), ts_01.max())

ts_01 = torch.randint(low=0, high=100, size=(3, 4)) # 0 ~ 99까지의 random value
print('ts_01:\n', ts_01, ts_01.dtype)
print(ts_01.min(), ts_01.max())

ts_01 = torch.randn(size=(3, 4)) # 평균이 0 이고, 분산이 1인 정규 분포 random value. 
print('ts_01:\n', ts_01, ts_01.dtype)
print(ts_01.min(), ts_01.max(), ts_01.mean(), ts_01.var())

ts_01:
 tensor([[0.6850, 0.9355, 0.2900, 0.3991],
        [0.7470, 0.0215, 0.0654, 0.7855],
        [0.3883, 0.6340, 0.9447, 0.4773]]) torch.float32
tensor(0.0215) tensor(0.9447)
ts_01:
 tensor([[61, 66, 46, 45],
        [56,  1, 35,  1],
        [23, 48, 88, 88]]) torch.int64
tensor(1) tensor(88)
ts_01:
 tensor([[-1.8030,  0.7348, -1.4956,  0.0521],
        [ 1.1838,  1.6855, -0.3477, -0.3971],
        [ 0.1480, -1.1127,  1.1575,  0.1298]]) torch.float32
tensor(-1.8030) tensor(1.6855) tensor(-0.0054) tensor(1.1970)


#### tensor의 형태(shape)를 변경하는 reshape()와 view()
* reshape()와 view() 모두 tensor의 형태를 변환하나 view()는 contiguous memory 구조에서만 동작됨.
* pytorch는 reshape()보다는 view() 호출을 권장. (강제로) tensor에서 contiguous memory 구조를 유지하기를 권장함.

In [23]:
import torch 

ts_01 = torch.arange(10)
print('ts_01:\n', ts_01)

ts_02 = ts_01.reshape((2, 5))
print('ts_02:\n',ts_02)

ts_03 = ts_01.reshape(5, 2)
print('ts_03:\n',ts_03)

ts_01:
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ts_02:
 tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
ts_03:
 tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [24]:
### 아래는 오류 발생 
ts_01.reshape(3, 4)

RuntimeError: shape '[3, 4]' is invalid for input of size 10

In [25]:
ts_02 = ts_01.view((2, 5))
print('ts_02:\n', ts_02, ts_02.shape)

ts_02:
 tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]) torch.Size([2, 5])


In [26]:
torch.manual_seed(2025) 

ts_01 = torch.rand(size=(16, 3, 32, 32))
ts_02 = ts_01.view(16, -1)
print(ts_02.shape)

torch.Size([16, 3072])


In [27]:
#기본적으로 tensor는 contiguous memory 구조로 생성됨. 
ts_01 = torch.arange(10)
ts_02 = ts_01.view(2, -1)
ts_03 = ts_01.reshape(2, -1)

print(ts_01.is_contiguous(), ts_02.is_contiguous(), ts_03.is_contiguous())

True True True


#### tensor의 차원 위치를 변경하여 재배열하는 permute(), t(), transpose()
* permute()는 차원의 위치를 자유롭게 변경할 수 있음.
* t()는 2차원 tensor의 row와 col을 변경.
* transpose()는 2개 차원의 위치만 변경할 수 있음.
* permute(), t(), transpose() 수행 시 contiguous memory가 구조가 깨지므로 view() 적용 시 유의 필요

In [28]:
torch.manual_seed(2025)

ts_01 = torch.rand(size=(64, 64, 3))
print(ts_01)

tensor([[[6.8497e-01, 9.3553e-01, 2.9004e-01],
         [3.9910e-01, 7.4704e-01, 2.1453e-02],
         [6.5449e-02, 7.8547e-01, 3.8830e-01],
         ...,
         [5.7394e-01, 6.7899e-01, 1.4175e-01],
         [1.0564e-01, 6.2005e-02, 5.4586e-01],
         [5.5911e-01, 9.6809e-01, 9.7254e-02]],

        [[9.9808e-01, 6.6539e-01, 8.2797e-02],
         [5.1192e-01, 6.0581e-01, 4.7461e-01],
         [4.6758e-01, 7.2692e-01, 6.9974e-01],
         ...,
         [8.4161e-02, 1.8078e-01, 6.4848e-01],
         [4.9513e-01, 1.9589e-01, 9.0705e-01],
         [8.4488e-01, 6.6279e-01, 9.3101e-01]],

        [[8.8574e-01, 9.4726e-01, 8.8349e-02],
         [2.6516e-01, 5.0015e-02, 1.8065e-01],
         [2.7291e-01, 5.1031e-01, 7.9525e-01],
         ...,
         [6.8054e-01, 6.4050e-01, 5.4171e-01],
         [3.6098e-01, 8.0259e-01, 9.6788e-01],
         [6.9853e-01, 1.8310e-01, 9.5629e-01]],

        ...,

        [[6.2225e-01, 5.3005e-01, 6.3497e-01],
         [5.0247e-01, 9.5379e-02, 4.5555e-03]

In [29]:
torch.manual_seed(2025)

ts_01 = torch.rand(size=(64, 64, 3))
print(ts_01.shape)

ts_02 = ts_01.permute(dims=(2, 0, 1)) # torch.permute(ts_01, dims=(2, 0, 1))
print(ts_02.shape)

ts_03 = ts_02.permute(dims=(1, 2, 0)) # torch.permute(ts_02, dims=(1, 2, 0))
print(ts_03.shape)

torch.Size([64, 64, 3])
torch.Size([3, 64, 64])
torch.Size([64, 64, 3])


In [30]:
ts_01 = torch.rand(size=(16, 32, 32, 3))
ts_02 = ts_01.permute(dims=(0, 3, 1, 2))
print(ts_02.shape)

torch.Size([16, 3, 32, 32])


In [31]:
ts_01 = torch.rand(size=(3, 64, 64))
ts_02 = torch.permute(ts_01, dims=(1, 2, 0)) #permute로 차원 이동 시 연속(contiguous) 메모리 구조가 깨질 수 있음.
print('ts_02 shape:', ts_02.shape)
print('is ts_02 contiguous? ', ts_02.is_contiguous())

ts_02 shape: torch.Size([64, 64, 3])
is ts_02 contiguous?  False


In [32]:
ts_02_1 = ts_02.view(64, -1)# permute로 차원 이동 시 연속(contiguous) 메모리 구조가 깨질 수 있음. 이 경우 view를 사용하면 안됨.

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [33]:
ts_01 = torch.rand(size=(3, 64, 64))
ts_02 = torch.permute(ts_01, dims=(1, 2, 0))

ts_02_1 = ts_02.reshape(64, -1) # reshape는 연속 메모리 구조와 관계없이 변환
print('ts_02_1 shape:', ts_02_1.shape)


ts_02_1 shape: torch.Size([64, 192])


In [34]:
ts_01 = torch.rand(size=(3, 64, 64))
ts_02 = torch.permute(ts_01, dims=(1, 2, 0))
print('ts_02 shape:', ts_02.shape)

ts_02_1 = ts_02.contiguous().view(64, -1) # contiguous()로 연속 메모리 구조 만든 후 view() 적용.

ts_02 shape: torch.Size([64, 64, 3])


In [35]:
ts_01 = torch.rand(size=(3, 4))
ts_02 = ts_01.t()
print('ts_02 shape:', ts_02.shape)

ts_02 shape: torch.Size([4, 3])


In [36]:
ts_01 = torch.rand(size=(64, 3, 128, 248))
ts_02 = ts_01.transpose(2, 3)
print('ts_02 shape:', ts_02.shape)

ts_02 shape: torch.Size([64, 3, 248, 128])


#### tensor에 sum, max, min, mean등의 aggregation 적용
* sum, max, min, mean등의 aggregation 메소드는 dim 인자를 가짐. dim이 None일 경우 전체 원소들에 aggregation 적용.
* dim인자는 해당 차원(axis 축)을 따라서(방향성으로) aggregation을 수행.
* 단일 차원의 dim인자를 적용하여 aggregation을 수행 할 경우 반환되는 tensor의 차원수는 원본 tensor의 차원 수 - 1임.
* 여러 차원의 dim인자를 적용하여 aggregation을 수행 할 경우 반환되는 tensor의 차원수는 원본 tensor의 차원 수 - 해당 dim 차원수임. 

In [21]:
ts_01 = torch.arange(10).view(2, 5)
ts_01.max()

tensor(9)

In [22]:
import torch 

ts_01 = torch.arange(10).view(2, 5)
print(ts_01)

print('total sum:', ts_01.sum())
print('sum along dim=0:', ts_01.sum(dim=0))
print('sum along dim=1:', ts_01.sum(dim=1))

print('max overall:', ts_01.max())
print('max along dim=0:', ts_01.max(dim=0))# max값과 max가 위치한 index값을 함께 반환. 
print('max along dim=1:', ts_01.max(dim=1))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
total sum: tensor(45)
sum along dim=0: tensor([ 5,  7,  9, 11, 13])
sum along dim=1: tensor([10, 35])
max overall: tensor(9)
max along dim=0: torch.return_types.max(
values=tensor([5, 6, 7, 8, 9]),
indices=tensor([1, 1, 1, 1, 1]))
max along dim=1: torch.return_types.max(
values=tensor([4, 9]),
indices=tensor([4, 4]))


In [37]:
print(ts_01)
print('overall mean:', ts_01.mean(dtype=torch.float64))
print('mean along dim=0:', ts_01.mean(dim=0, dtype=torch.float64))
print('mean along dim=1:', ts_01.mean(dim=1, dtype=torch.float64))

print('min overall:', ts_01.min())
print('min along dim=0:', ts_01.min(dim=0))# min값과 min이 위치한 index값을 함께 반환. 
print('min along dim=1:', ts_01.min(dim=1))

tensor([[[[0.6335, 0.1099, 0.0149,  ..., 0.2430, 0.3917, 0.1999],
          [0.1033, 0.2894, 0.7031,  ..., 0.0234, 0.6310, 0.7200],
          [0.7143, 0.6883, 0.9132,  ..., 0.2962, 0.9564, 0.3480],
          ...,
          [0.6361, 0.8075, 0.7447,  ..., 0.7073, 0.0075, 0.9899],
          [0.7209, 0.5302, 0.6207,  ..., 0.9144, 0.1500, 0.1958],
          [0.7484, 0.8991, 0.0279,  ..., 0.5883, 0.0924, 0.0875]],

         [[0.4549, 0.4800, 0.6778,  ..., 0.4058, 0.0507, 0.2481],
          [0.5892, 0.3991, 0.9660,  ..., 0.2820, 0.0866, 0.3481],
          [0.5252, 0.1388, 0.7346,  ..., 0.3005, 0.7434, 0.4079],
          ...,
          [0.9005, 0.9332, 0.2450,  ..., 0.3190, 0.5345, 0.8825],
          [0.6825, 0.3160, 0.9577,  ..., 0.6890, 0.4037, 0.7594],
          [0.7855, 0.4750, 0.0240,  ..., 0.4860, 0.9674, 0.7318]],

         [[0.4826, 0.4516, 0.5195,  ..., 0.9992, 0.7352, 0.1057],
          [0.4194, 0.7260, 0.4793,  ..., 0.9997, 0.7695, 0.0804],
          [0.7762, 0.7646, 0.7574,  ..., 0

In [38]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [39]:
ts_02 = torch.arange(24).reshape(2, 3, 4)
print(ts_02)

print('total sum:', ts_02.sum())
print('sum along dim=0:\n', ts_02.sum(dim=0))
print('sum along dim=1:\n', ts_02.sum(dim=1))
print('sum along dim=2:\n', ts_02.sum(dim=2))
print('sum along dim=-1:\n', ts_02.sum(dim=-1))

print('max overall:', ts_02.max())
print('max along dim=0:', ts_02.max(dim=0))# max값과 max가 위치한 index값을 함께 반환. 
print('max along dim=1:', ts_02.max(dim=1))

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
total sum: tensor(276)
sum along dim=0:
 tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])
sum along dim=1:
 tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])
sum along dim=2:
 tensor([[ 6, 22, 38],
        [54, 70, 86]])
sum along dim=-1:
 tensor([[ 6, 22, 38],
        [54, 70, 86]])
max overall: tensor(23)
max along dim=0: torch.return_types.max(
values=tensor([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
indices=tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]))
max along dim=1: torch.return_types.max(
values=tensor([[ 8,  9, 10, 11],
        [20, 21, 22, 23]]),
indices=tensor([[2, 2, 2, 2],
        [2, 2, 2, 2]]))


In [40]:
print(ts_02)
print('sum along dim=(1, 2):\n', ts_02.sum(dim=(1, 2)))
print('sum along dim=(2, 1):\n', ts_02.sum(dim=(2, 1)))

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
sum along dim=(1, 2):
 tensor([ 66, 210])
sum along dim=(2, 1):
 tensor([ 66, 210])


In [41]:
print(ts_02)
print('sum along dim=(0, 1):\n', ts_02.sum(dim=(0, 1)))
print('sum along dim=(1, 0):\n', ts_02.sum(dim=(1, 0)))

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
sum along dim=(0, 1):
 tensor([60, 66, 72, 78])
sum along dim=(1, 0):
 tensor([60, 66, 72, 78])


In [42]:
print(ts_02)
print('sum along dim=(-1):\n', ts_02.sum(dim=(-1)))
print('sum along dim=(-2, -1):\n', ts_02.sum(dim=(-2, -1)))

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
sum along dim=(-1):
 tensor([[ 6, 22, 38],
        [54, 70, 86]])
sum along dim=(-2, -1):
 tensor([ 66, 210])


#### argmax() 수행
* max()는 tensor내의 가장 큰 값을 반환하지만, argmax()는 가장 큰값을 가지는 index를 반환. 

In [43]:
torch.manual_seed(2025)  # random 수행 시 마다 동일 값 생성을 위한 seed값 할당. 

ts_01 = torch.rand(size=(10,))
print(ts_01)
print(ts_01.max(), ts_01.argmax())

tensor([0.6850, 0.9355, 0.2900, 0.3991, 0.7470, 0.0215, 0.0654, 0.7855, 0.3883,
        0.6340])
tensor(0.9355) tensor(1)


In [44]:
torch.manual_seed(2025)

ts_01 = torch.rand(size=(4, 5))
print(ts_01)
print(ts_01.argmax(dim=-1))

tensor([[0.6850, 0.9355, 0.2900, 0.3991, 0.7470],
        [0.0215, 0.0654, 0.7855, 0.3883, 0.6340],
        [0.9447, 0.4773, 0.2861, 0.3887, 0.1099],
        [0.3606, 0.8450, 0.8059, 0.0520, 0.3438]])
tensor([1, 2, 0, 1])


In [45]:
# dim값이 입력된 max()는 max값과 max위치의 index를 반환
print(ts_01.max(dim=-1))

torch.return_types.max(
values=tensor([0.9355, 0.7855, 0.9447, 0.8450]),
indices=tensor([1, 2, 0, 1]))


In [46]:
_, val_index = ts_01.max(dim=-1)
print( val_index)

tensor([1, 2, 0, 1])


In [47]:
print(ts_01.argmax(dim=0))

tensor([2, 0, 3, 0, 0])


#### squeeze()와 unsqueeze()
* squeeze()는 1로 되어 있는 차원값을 없앤 tensor반환. unsqueeze는 기존 차원을 1차원 증가시킴.
* squeeze(dim=0)과 같이 해당 dim을 지정하면 해당 차원값만(1로 되어 있어야 함) 삭제하여 재 구성한 tensor 반환
* squeeze(dim=None)은 1로 되어 있는 차원값을 모두 찾아서 없앤 tensor 반환.
* unsqueeze()는 dim=0과 같이 반드시 dim인자를 입력해 줘야 함(squeeze()도 가급적이면 반드시 dim인자 입력)

In [48]:
torch.manual_seed(2025)

ts_01 = torch.rand(size=(1, 4, 5))
print(ts_01)

ts_01_1 = ts_01.squeeze()
print('ts_01 shape:', ts_01.shape, 'ts_01 squeezed shape:', ts_01_1.shape)
print(ts_01_1)

tensor([[[0.6850, 0.9355, 0.2900, 0.3991, 0.7470],
         [0.0215, 0.0654, 0.7855, 0.3883, 0.6340],
         [0.9447, 0.4773, 0.2861, 0.3887, 0.1099],
         [0.3606, 0.8450, 0.8059, 0.0520, 0.3438]]])
ts_01 shape: torch.Size([1, 4, 5]) ts_01 squeezed shape: torch.Size([4, 5])
tensor([[0.6850, 0.9355, 0.2900, 0.3991, 0.7470],
        [0.0215, 0.0654, 0.7855, 0.3883, 0.6340],
        [0.9447, 0.4773, 0.2861, 0.3887, 0.1099],
        [0.3606, 0.8450, 0.8059, 0.0520, 0.3438]])


In [49]:
# squeeze(dim=0)과 같이 dim 인자 적용
ts_01 = torch.rand(size=(1, 4, 1))
ts_01_1 = ts_01.squeeze(dim=0)
ts_01_2 = ts_01.squeeze(dim=-1)
ts_01_3 = ts_01.squeeze(dim=(0, -1))

print(ts_01.shape, ts_01_1.shape, ts_01_2.shape, ts_01_3.shape)

torch.Size([1, 4, 1]) torch.Size([4, 1]) torch.Size([1, 4]) torch.Size([4])


In [50]:
# 보통은 batch가 포함된 4차원 이미지 tensor에서 batch가 1일 경우 3차원 단일 이미지 tensor로 변환하는데 주로 사용 
ts_01 = torch.rand(size=(1, 3, 64, 64))
ts_01_1 = ts_01.squeeze(dim=0)
print('ts_01 shape:', ts_01.shape, 'ts_01 squeezed shape:', ts_01_1.shape)

ts_01 shape: torch.Size([1, 3, 64, 64]) ts_01 squeezed shape: torch.Size([3, 64, 64])


In [51]:
torch.manual_seed(2025)

ts_01 = torch.rand(size=(4, 5))
print(ts_01)

ts_01_1 = ts_01.unsqueeze(dim=0) # dim 인자가 반드시 사용되어야 함. 
print('ts_01 shape:', ts_01.shape, 'ts_01 unsqueezed shape:', ts_01_1.shape)
print(ts_01_1)

tensor([[0.6850, 0.9355, 0.2900, 0.3991, 0.7470],
        [0.0215, 0.0654, 0.7855, 0.3883, 0.6340],
        [0.9447, 0.4773, 0.2861, 0.3887, 0.1099],
        [0.3606, 0.8450, 0.8059, 0.0520, 0.3438]])
ts_01 shape: torch.Size([4, 5]) ts_01 unsqueezed shape: torch.Size([1, 4, 5])
tensor([[[0.6850, 0.9355, 0.2900, 0.3991, 0.7470],
         [0.0215, 0.0654, 0.7855, 0.3883, 0.6340],
         [0.9447, 0.4773, 0.2861, 0.3887, 0.1099],
         [0.3606, 0.8450, 0.8059, 0.0520, 0.3438]]])


In [52]:
# 보통은 3차원 단일 이미지 tensor를 batch 포함 4차원 이미지 tensor로 변환 시 자주 사용
ts_01 = torch.rand(size=(3, 64, 64))
ts_01_1 = ts_01.unsqueeze(dim=0)
print('ts_01 shape:', ts_01.shape, 'ts_01 unsqueezed shape:', ts_01_1.shape)

ts_01 shape: torch.Size([3, 64, 64]) ts_01 unsqueezed shape: torch.Size([1, 3, 64, 64])


In [53]:
torch.tensor([1])

tensor([1])

#### item() 
* tensor 자체가 아니라 tensor값만 반환하는 데 사용. tensor가 값을 1개만 가지고 있을 경우 이 값을 python scalar 값으로 반환
* 1차원 tensor에 값이 하나만 있거나 tensor가 scalar type일 경우만 item() 가능.

In [54]:
ts_01 = torch.tensor([1])
print(ts_01.dtype, ts_01.shape, ts_01.ndim)
print('ts_01 item():', ts_01.item())

ts_02 = torch.tensor(1)
print(ts_02.dtype, ts_02.shape, ts_02.ndim)


torch.int64 torch.Size([1]) 1
ts_01 item(): 1
torch.int64 torch.Size([]) 0


In [55]:
# 아래는 1차원 이지만 값이 2개 이상이므로 item() 호출 시 오류 발생. 
ts_01 = torch.tensor([1, 2])
print(ts_01.dtype, ts_01.shape, ts_01.ndim)
print('ts_01 item():', ts_01.item())

torch.int64 torch.Size([2]) 1


RuntimeError: a Tensor with 2 elements cannot be converted to Scalar

#### indexing
* tensor의 indexing은 numpy array indexing과 매우 유사
* 단일 지정(integer) indexing, 슬라이싱(:) indexing, Fancy(List) indexing, Boolean indexing 외에도 다양한 indexing을 제공
* 단일 지정 indexing을 수행 할 경우 원본 tensor를 한 차원 줄인 tensor반환(numpy array도 마찬가지)
* numpy와 다르게 pytorch boolean indexing을 1차원 tensor를 반환(numpy array는 원본 차원 유지)


In [56]:
ts_01 = torch.arange(0, 10).view(2, 5)
print(ts_01)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [57]:
# 지정 인덱싱 적용
print('ts_01[0, 0]:', ts_01[0, 0], 'ts_01[0, 1]:', ts_01[0, 1])
print('ts_01[1, 0]:', ts_01[1, 0], 'ts_01[1, 2]:', ts_01[1, 2])
print(ts_01[0, 0].shape, ts_01[0, 0].ndim, ts_01[0, :].shape, ts_01[0, :].ndim)

ts_01[0, 0]: tensor(0) ts_01[0, 1]: tensor(1)
ts_01[1, 0]: tensor(5) ts_01[1, 2]: tensor(7)
torch.Size([]) 0 torch.Size([5]) 1


In [58]:
print(ts_01)
print('ts_01[0, :]은', ts_01[0, :], 'ts_01[:, 0]은', ts_01[:, 0])
print('ts_01[0, 0:3]은', ts_01[0, 0:3], 'ts_01[1, 1:4]은', ts_01[1, 1:4])
print('ts_01[:, :]\n', ts_01[:, :])

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
ts_01[0, :]은 tensor([0, 1, 2, 3, 4]) ts_01[:, 0]은 tensor([0, 5])
ts_01[0, 0:3]은 tensor([0, 1, 2]) ts_01[1, 1:4]은 tensor([6, 7, 8])
ts_01[:, :]
 tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [59]:
torch.manual_seed(2025)

random_indexes = torch.randint(0, 5, size=(4,))
print('random_indexes:', random_indexes)

random_indexes: tensor([1, 4, 4, 1])


In [60]:
torch.manual_seed(2025)

random_indexes = torch.randint(0, 5, size=(4,))
print('random_indexes:', random_indexes)

ts_01 = torch.rand(size=(10, 5))
print('ts_01:\n', ts_01)

ts_01_1 = ts_01[random_indexes] # fancy indexing 적용
print('ts_01_1:\n', ts_01_1)

random_indexes: tensor([1, 4, 4, 1])
ts_01:
 tensor([[0.7470, 0.0215, 0.0654, 0.7855, 0.3883],
        [0.6340, 0.9447, 0.4773, 0.2861, 0.3887],
        [0.1099, 0.3606, 0.8450, 0.8059, 0.0520],
        [0.3438, 0.5326, 0.5318, 0.0709, 0.8716],
        [0.6798, 0.2956, 0.9812, 0.9813, 0.8118],
        [0.0463, 0.9592, 0.5132, 0.3941, 0.6953],
        [0.7350, 0.0309, 0.8294, 0.3368, 0.6413],
        [0.6471, 0.5964, 0.9792, 0.8084, 0.9328],
        [0.8772, 0.1945, 0.5616, 0.6019, 0.5040],
        [0.0028, 0.2127, 0.0655, 0.0905, 0.2134]])
ts_01_1:
 tensor([[0.6340, 0.9447, 0.4773, 0.2861, 0.3887],
        [0.6798, 0.2956, 0.9812, 0.9813, 0.8118],
        [0.6798, 0.2956, 0.9812, 0.9813, 0.8118],
        [0.6340, 0.9447, 0.4773, 0.2861, 0.3887]])


In [61]:
ts_01 = torch.arange(0, 10).view(2, 5)
print(ts_01)

mask = ts_01 > 4
print(mask)
print(ts_01[mask]) # pytorch tensor의 boolean indexing은 1차원 tensor를 반환.

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[False, False, False, False, False],
        [ True,  True,  True,  True,  True]])
tensor([5, 6, 7, 8, 9])


In [ ]:
# where는 원본 배열 차원을 보존
torch.where(ts_01 > 4, input=ts_01, other=torch.tensor(999))

#### 내적과 행렬곱 연산 - dot()와 matmul()
* torch의 dot() 연산은 1차원 tensor만 가능(vector dot product)
* torch의 matmul() 연산은 1차원-2차원 tensor간, 2차원 tensor간(matrix) 행렬곱 연산 수행
* matmul()의 경우 3차원 이상의 tensor가 입력될 경우 맨 뒤의 2개 차원을 행렬로, 앞의 차원들은 batch로 간주하고 행렬곱 연산 수행
![행렬곱](https://github.com/chulminkw/CNN_PG_Torch/blob/main/image/matmul.png?raw=true)

In [62]:
import torch 

ts_01 = torch.arange(1, 4)
ts_02 = torch.arange(4, 7)
print('ts_01:', ts_01, 'ts_02:', ts_02)

ts_03 = torch.dot(ts_01, ts_02) # dot()연산은 1차원끼리만 가능. 
print('ts_03:', ts_03)

ts_01: tensor([1, 2, 3]) ts_02: tensor([4, 5, 6])
ts_03: tensor(32)


In [63]:
ts_01 = torch.arange(1, 7).view(2, 3)
ts_02 = torch.arange(7, 13).view(3, 2)
print('ts_01:\n', ts_01, '\n', 'ts_02:\n', ts_02)

ts_03 = torch.matmul(ts_01, ts_02) # 2차원 행렬 곱 연산 수행
print('ts_03:\n', ts_03)

ts_01:
 tensor([[1, 2, 3],
        [4, 5, 6]]) 
 ts_02:
 tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])
ts_03:
 tensor([[ 58,  64],
        [139, 154]])


In [64]:
# 3차원 이상의 행렬 곱. batch size는 서로 동일해야 함. 단 둘중 한개가 batch size 1인 경우는 상관 없음. 
ts_01 = torch.arange(0, 24).view(2, 3, 4) # batch size 2를 가지는 3x4 행렬
ts_02 = torch.arange(0, 40).view(2, 4, 5)  # batch size 2을 가지는 4x5 행렬
print('ts_01:\n', ts_01, '\n', 'ts_02:\n', ts_02)

ts_03 = torch.matmul(ts_01, ts_02)  # 맨 앞차원은 배치로 간주하고 뒤 차원 2개를 행렬 곱 연산 수행. 
print('ts_03:\n', ts_03)
print(ts_03.shape) # 출력 shape는 (2, 3, 5)

ts_01:
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]) 
 ts_02:
 tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]])
ts_03:
 tensor([[[  70,   76,   82,   88,   94],
         [ 190,  212,  234,  256,  278],
         [ 310,  348,  386,  424,  462]],

        [[1510, 1564, 1618, 1672, 1726],
         [1950, 2020, 2090, 2160, 2230],
         [2390, 2476, 2562, 2648, 2734]]])
torch.Size([2, 3, 5])


In [65]:
torch.matmul(
torch.tensor(
[[ 0,  1,  2,  3],
[ 4,  5,  6,  7],
[ 8,  9, 10, 11]]), 
torch.tensor(
[[ 0,  1,  2,  3,  4],
[ 5,  6,  7,  8,  9],
[10, 11, 12, 13, 14],
[15, 16, 17, 18, 19]]
))

tensor([[ 70,  76,  82,  88,  94],
        [190, 212, 234, 256, 278],
        [310, 348, 386, 424, 462]])

In [66]:
# batch size는 서로 동일해야 함. 단 둘중 한개가 batch size 1인 경우는 상관 없음.
ts_01 = torch.arange(0, 24).view(2, 3, 4) # batch size 2를 가지는 3x4 행렬
ts_02 = torch.arange(0, 60).view(3, 4, 5)  # batch size=3을 가지는 4x5 행렬
print('ts_01:\n', ts_01, '\n', 'ts_02:\n', ts_02)

ts_03 = torch.matmul(ts_01, ts_02)  # 맨 앞차원은 배치로 간주하고 뒤 차원 2개를 행렬 곱 연산 수행. 
print(ts_03)
print(ts_03.shape)

ts_01:
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]) 
 ts_02:
 tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0